### ISSUE TITLE
Will you provide pre-trained model trained on CALVIN dataset?

### ISSUE THREAD

**Issue by Anchoret13** [mees/hulc2#2]
Great work! It's very impressive, but I am wondering if there is any possibility that you could provide pre-trained models specifically trained on the CALVIN dataset. On CALVIN website, HULC++ is current SOTA, could you please provide that version of model?

Thanks so much!

**Comment by mees** [comment]
Sadly we don't have access to the pre-trained models for CALVIN as both Jessica and me are no longer affiliated with the lab where this research project was performed. Hopefully with the training instructions it should be reproducible though. Also, there are new SOTA models on CALVIN.
